### ISSUE TITLE
Alternate binary locations

### ISSUE THREAD

**Issue by MrHavard** [imagemin/gifsicle-bin#77]
Due to proxy issues we can't download the binaries via the install script. Is there anyway to provide an alternate path to retrieve the binaries from an internal repo or NPM/artifactory location?

**Comment by sindresorhus** [comment]
Open an issue on https://github.com/kevva/bin-wrapper to support alternative binary locations.

**Comment by zend** [comment]
https://github.com/imagemin/gifsicle-bin/blob/26d16d6fdd4f87802cf3f43f0e42bf11bf1b1780/lib/index.js#L6

When behind a proxy, a direct connect to `raw.githubusercontent.com` may fail. If the `url` in this code can be changed in environment variable, the problem can be solved.

Issues like https://github.com/kevva/bin-wrapper/issues/50 and https://github.com/kevva/bin-wrapper/issues/62 is placed over two years without response. In fact, there are a lot `Alternate binary locations` maintained by community, like `https://raw.github.cnpmjs.org/imagemin/`, and we can replace the domain name and solve the problem here in this code.

**Comment by 06kellyjac** [comment]
> Open an issue on [kevva/bin-wrapper](https://github.com/kevva/bin-wrapper) to support alternative binary locations.

That's a pretty weird thing to say when you looked at a PR adding alternative binary support to kevva/bin-wrapper that same day only a couple minutes beforehand

https://github.com/kevva/bin-wrapper/pull/56#issuecomment-354163643
