### ISSUE TITLE
Use `bin-build` 3.x?

### ISSUE THREAD

**Issue by NoelLH** [imagemin/gifsicle-bin#78]
Hi, I'm a newbie to this package but was just looking into a dependency chain via `imagemin-gifsicle` and the latest `gifsicle@3.0.4`.

[Snyk reports](https://snyk.io/test/npm/grunt-contrib-imagemin/2.0.1) that there's a vulnerability via `bin-build`'s fixed-version dependency chain, which leads to a vulnerable version of `tunnel-agent`.

Is it possible to upgrade to `bin-build@^3.0.0`? I tried it with this repo but I think I have something more fundamentally misconfigured that's stopping `npm test` for this package in isolation working on my local.

**Comment by jigar1101** [comment]
I believe @kevva has updated the bin-build to ^3.0.0 in this [commit](https://github.com/imagemin/gifsicle-bin/commit/7f88f03e5def54531cf6f25db53e4e2da2cd8c4b?diff=split)

But on doing `npm install gifsicle-bin` for version `3.0.4`, its package.json is still showing the bin-build version as `2.2.0`

@kevva Is it because the new version is not published to the npm repository or may be we need to update the package.json to 3.0.5 for the changes to take effect? 
Can you please throw some light? I'll create a PR with the necessary changes.

P.S - I'm facing this in the usage of `grunt-contrib-imagemin@2.0.1` which uses `imagemin-gifsicle@5.2.0` and which uses `gifsicle@3.0.4` (Same as @NoelLH )

**Comment by 1000ch** [comment]
Fixed on the newest version.
